import './label.js'

/**
 * Testing custom element generation patterns
 */
export default class X3ways extends HTMLElement {
  /**
   * Attach
   */
  connectedCallback() {
    this._render();
  }

  /**
   * Render
   * @private
   */
  _render() {
    this.innerHTML = `
      <h1>Three ways to generate CustomElements</h1>
      <!-- ① Declarative tag writing pattern -->
      <x-label label="① hello"></x-label>
    `;

    // ② Generated by new operator
    const Label = window.customElements.get('x-label');
    const labelElmA = new Label('② hello');
    this.appendChild(labelElmA);
    // ③ Generated by DOM API
    const labelElmB = document.createElement('x-label');
    labelElmB.label = '③ hello';
    this.appendChild(labelElmB);
  }
}

// Register custom element
window.customElements.define('x-3ways', X3ways);
